services:
  mysql:
    container_name: mysql-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql-ip_embarca
volumes:
  mysql_data:
